config/routes.rb
Rails.application.routes.draw do 
  root 'barbers#shop'  
  get 'login', to: 'customers#login'
  get 'logout', to: 'application#logout' 
  post 'login_user', to: 'customers#login_user' 
  post '/filter', to: 'haircuts#filter'
  get '/auth/facebook/callback' => 'customers#fbook'
  get 'haircuts/schedule', to: 'haircuts#index'  
  post 'customers/customer_slug/haircuts/new', to: 'haircuts#create'
  resources :haircuts
  resources :appointments
  resources :customers, param: :slug do 
    resources :haircuts, only: [:new, :show, :destroy ]
  end  
  resources :customers, param: :slug do 
    resources :appointments, only: [:new, :show]  
  end
  resources :barbers, param: :slug
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partial/_app.html.erb
<%= form_for(app) do |f| %>
    
 <% if params.keys.include?("slug") %> 
 <% current_barber = params["slug"] %>
 <%= f.select :barber, current_barber => current_barber  %> 
 <% end %>
<%= f.hidden_field :customer_id  %> 

<%= f.select :service, options_for_select(@collection.uniq) %> 
<%= datetime_select( 'datetime' ,:date, {:minute_step => 15} )  %>
<%= f.submit %>
<% end %>

app/views/partial/_customer.html.erb
<div class='<%= "first" if flash[:error] %>' > 
<%= form_for @customer do |f| %> 
<%= f.label :name %> 

<%= f.text_field :name %> 
<br>
<%= f.label :email %>
<%= f.text_field :email %>
<br>
<%= f.label :phone_number, 'phone number' %>
<%= f.text_field :phone_number  %>
<br>
<%= f.label 'password' %>
<%= f.text_field :password %>
<br>
<%= f.label :password_confirmation %>
<%= f.text_field :password_confirmation %>
<br> 
<%= f.submit 'register' %>
<% end %> 
</div>

app/views/partial/_cut.html.erb
<%= form_for(haircut, url: '/customers/customer_slug/haircuts/new' ) do |f| %> 

<%= f.label :style  %>
<%= f.text_field :style %>
<br> 
<%= f.label :date %> 
<br>

<%= datetime_select( 'datetime' ,:date, {:minute_step => 15} )  %>


 <% if params.keys.include?("slug") %> 
 <% current_barber = params["slug"] %>
 <%= f.select :barber, current_barber => current_barber  %>
 <% else %>
<%= f.select :barber, options_for_select(Barber.all.map{ |x| x.name })%>
<% end %>
  <br>
  
  <% if haircut.customer_id.blank? %>
  <%= f.text_field :customer_id %> 
  <% else %>
  <%= f.hidden_field :customer_id  %>
  <% end %>
<%= f.submit %>
<% end %> 

app/views/partial/_nav.html.erb
<% if session[:customer_slug] || current_user.nil?  %>

<nav class="nav"><%= link_to 'schedule', haircuts_schedule_path %> | <%= link_to 'logout', logout_path %> | <%= link_to 'barbers', barbers_path %> | <%= link_to 'profile', customer_path(current_user) unless current_user.nil? %> | <%= link_to 'schedule a haircut', new_haircut_path %></nav>
<% end %>                                          

app/views/partial/_signin.html.erb
<%= form_for(@customer, url: login_user_path) do |f| %> 

<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit 'login' %> 
<% end %> 

app/views/partial/_sub_nav.html.erb
<nav><%= link_to "Sign in", login_path unless session["page"] == "signin" %> | <%= link_to "Register", new_customer_path %> | <%= link_to 'homepage', root_path unless session["page"] == "home" %> | <%= link_to('Log in with Facebook!', '/auth/facebook') %></nav>

app/views/partial/_up.html.erb
<%= form_for @customer do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.text_field :password %> 
<%= f.label 'password confirmation' %>
<%= f.text_field :password_confirmation %> 
<%= f.submit %>
<% end %>