config/routes.rb
Rails.application.routes.draw do 
  root 'barbers#shop'  
  get 'login', to: 'customers#login'
  get 'logout', to: 'application#logout' 
  post 'login_user', to: 'customers#login_user' 
  post '/filter', to: 'haircuts#filter'
  get '/auth/facebook/callback' => 'customers#fbook'
  get 'haircuts/schedule', to: 'haircuts#index'  
  post 'customers/customer_slug/haircuts/new', to: 'haircuts#create'
  resources :haircuts
  resources :appointments
  resources :customers, param: :slug do 
    resources :haircuts, only: [:new, :show, :destroy ]
  end  
  resources :customers, param: :slug do 
    resources :appointments, only: [:new, :show]  
  end
  resources :barbers, param: :slug
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord  
    
    attr_accessor :uid

    has_secure_password
    has_many :appointments 
    has_many :barbers, through: :appointments 
    has_many :haircuts 
    has_many :barbers, through: :haircuts 
    
    validates :name, presence: true
    validates :email, :phone_number, presence: true, uniqueness: true 
    accepts_nested_attributes_for :barbers, :haircuts, :barbers 

    before_create :set_slug  
  
    def to_param  
        
        slug
        
    end 

    def self.find_by_slug(params)
        Article.where('slug' == params['slug']).first
    end 

    private 

     def set_slug
    
      self.slug = SecureRandom.uuid
      
     end 

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController  
    helper_method :current_user, :logged_in? 
    before_action :require_login
    skip_before_action :require_login, only: [:login, :new, :login_user, :fbook, :create]
    
   
   
   
    def fbook
        @auth_name = auth['info']['name'] 
        
        if @auth_name 
            @on_Fbook = true 
                
                @customer = Customer.find_by(name: @auth_name)  
                @in_db = true
                if @customer  
                   session[:message] = 'Welcome FACEBOOK USER!' 
                   session[:customer_slug] = @customer.slug  
                else 
                    @in_db = false
                    session[:errors] = "User is not registered under Shopy"  
                    session[:errors] = "Login a different way or Regester with us!"
                end
        else  
            @flag = false
            session[:errors] = "User does not exist on Facebook and or Shopy" 
            session[:message] = "Login a different way!"
        end
        redirect_to @in_db ? customer_path(@customer) : login_path
    end

    def login  
        session["page"] = "signin"
         @customer = Customer.new
    end 
    def new   
        session[:page] = 'new'
        @customer = Customer.new
    end 
    def login_user
         
        password = params[:customer][:password]
        email = params[:customer][:email] 
        
        @customer = Customer.find_by(email: email)
         
        
        if      @customer.try(:authenticate, password)  
            
            session[:slug] = @customer.slug
            session[:customer_slug] = @customer.slug
            @switch = true
        else
            @switch = false 
            @customer.nil? ? session[:errors] = "Email not found." : session[:errors] = 'Password incorrect.' 
            session[:page] = 'login'
        end  
   
        redirect_to @switch ? customer_path(@customer) : @customer.nil? ? {action: :new} : {action: :login}
    end 

    def create  
        
        @customer = Customer.create(customer_params) 
        session[:customer_slug] = @customer.slug 
        
        if @customer.valid?
            redirect_to customer_path(@customer) 
        else 
            flash[:error] = 'one or more problmes' 
            flash[:full_errors] = @customer.errors.details 
            redirect_to action: :new
        end

    end  

    def show  
        
        session[:page] = 'profile' 
        @customer = Customer.find_by(slug: params[:slug])  
        session[:customer_slug] = @customer.slug  
       
        @session = session
        
    end 

    def logout 
        session.clear 
        redirect_to root_path 
    end 
    def destroy 
        binding.pry
    end
private 

    def auth
        request.env['omniauth.auth']
    end
    
    def customer_params 
        params.require('customer').permit('name', 'phone_number', 'email', 'password', 'password_confirmation')
    end
    
end

app/helpers/customers_helper.rb
module CustomersHelper 

    def current_u(x: y)
        Customers.where(x: y)
    end
end

app/views/customers/login.html.erb
<% if session[:errors] %>
<div class='first'>
<%= session[:errors] if session[:errors] %>

retry or <%= link_to 'Sign up', new_customer_path if session[:errors] %>
</div> 
<%end %> 
<br>
<%= link_to "Register", new_customer_path %> | <%= link_to 'homepage', root_path %> | <%= link_to('Log in with Facebook!', '/auth/facebook') %>
<br>
<%= render 'partial/signin' %>

app/views/customers/new.html.erb
<% if flash[:full_errors]  %>
<ul>
<% flash[:full_errors].each do |k,v| %>
    <li><h2 class='red'><%=k %></h2></li> 
    <% v.first.each do |x,y| %>
        <p>cannot be <%= y %></p>
        
        <%end%> 
     
        
    <% end %>

</ul>
    <% else %> 

    <h1 class="first"><%= session[:errors] %></h1><h4><%= link_to 'Sign In', login_path %> or Register Below</h4> 
    
    <% end %>
<% if flash[:error] %> 
    <div class="first"><h3 class='red'><%= flash[:error] %></h3> 

    </div>  
    
    <% end %> 
<%= render 'partial/sub_nav' %>
<%= render 'partial/customer' %>

app/views/customers/show.html.erb
<% if logged_in? %>
<h1 class='first'><%= session[:message] if session[:message] %></h1>
<div class='customer'>
<h1 class='red'><b>Hi <%= @customer.name %>!</b></h1> 
<ul><li><%= @customer.haircuts.count  %> cuts with us.</li>
<ol>
<% style_collection = @customer.haircuts.map{|cut| cut.style } %>
<% style_collection.uniq.each do |style| %>
<li><%= style %> style</li>
<% end %>
</ul> 

<% if @customer.haircuts.count == 0 %>
    <h1><%= @customer.name %> you have nothing scheduled! </h1><%= link_to 'go get a cut!', new_customer_haircut_path(@customer) %> 
<% else %>
<ul>
<% @customer.haircuts.each do |haircut| %> 
    <li><%= haircut.date.to_time.strftime("Haircut on %A, %b %e at %l %M %p") %></li> 
    <li><%= link_to "delete", haircut_path(haircut), method: 'delete' %></li> 
   <% end %> 
</ul>
<% end %>
    <p><%= link_to 'schedule a haircut', new_customer_haircut_path(@customer) %></p>
<% barber_count = @customer.barbers.uniq.count  %>
<li><%= barber_count %> Barbers cut your hair.<li/> 
<ol>
<%  @customer.barbers.all.uniq.each do |x| %>

<li><%= link_to x.name, barber_path(x) %></li> 
    <% end %> 
</ol>
</ul>
</div> 
<% else %> 
<div class='first'>
<h1> Please Login <h1>  
</div>
<% end %>